import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Architecture Decision Records.
 *
 * These replace what started as a single growing DECISIONS.md, and the reason
 * is mechanical rather than stylistic. Every task is told to read the prior
 * decisions before it starts. A single append-only file means that read costs
 * more on every task, until eventually a task reads it partially or skips it
 * — silently, and precisely on the long runs where prior context matters most.
 *
 * One file per decision fixes that. Tasks read the INDEX, which is one line
 * per decision and stays small, then open only the records that bear on their
 * work. Cost per task is roughly flat in the number of decisions.
 *
 * Division of labour: agents write the records, Kalfa regenerates the index by
 * scanning the directory. Nothing depends on an agent remembering to update
 * two files, and the index cannot drift from what is on disk.
 */

export const ADR_DIR = join('docs', 'adr');

export interface AdrEntry {
  number: number;
  title: string;
  status: string;
  /** Task id that produced it, when the record names one. */
  task?: string;
  file: string;
}

const ADR_FILE = /^(\d{4})-(.+)\.md$/;

export function ensureAdrDir(cwd: string): string {
  const dir = join(cwd, ADR_DIR);
  mkdirSync(dir, { recursive: true });
  return dir;
}

/** Parse one record's header. Tolerant: a malformed ADR still gets indexed. */
export function parseAdr(fileName: string, content: string): AdrEntry | undefined {
  const match = ADR_FILE.exec(fileName);
  if (!match) return undefined;

  const heading = content.match(/^#\s+(?:\d{4}[.\s-]+)?(.+)$/m);
  const status = content.match(/^-\s*\*\*Status:\*\*\s*(.+)$/m);
  const task = content.match(/^-\s*\*\*Task:\*\*\s*(.+)$/m);

  return {
    number: Number(match[1]),
    title: heading?.[1]?.trim() ?? match[2]!.replace(/-/g, ' '),
    status: status?.[1]?.trim().toLowerCase() ?? 'unknown',
    ...(task?.[1] ? { task: task[1].trim() } : {}),
    file: fileName,
  };
}

export function readAdrs(cwd: string): AdrEntry[] {
  const dir = join(cwd, ADR_DIR);
  if (!existsSync(dir)) return [];

  return readdirSync(dir)
    .filter((name) => ADR_FILE.test(name))
    .flatMap((name) => {
      try {
        const entry = parseAdr(name, readFileSync(join(dir, name), 'utf8'));
        return entry ? [entry] : [];
      } catch {
        return [];
      }
    })
    .sort((a, b) => a.number - b.number);
}

/** The number an agent should use for its next record. */
export function nextAdrNumber(cwd: string): number {
  const adrs = readAdrs(cwd);
  return adrs.length === 0 ? 1 : Math.max(...adrs.map((a) => a.number)) + 1;
}

export function renderAdrIndex(entries: AdrEntry[]): string {
  const lines = [
    `# Architecture Decisions`,
    ``,
    `Index regenerated by Kalfa from the files in this directory — edits here`,
    `are lost. Edit the records themselves.`,
    ``,
    `Each record is a decision that was made instead of stopping to ask. Read`,
    `this index before starting work; open only the records that bear on it.`,
    ``,
  ];

  if (entries.length === 0) {
    lines.push(`No decisions recorded yet.`, ``);
  } else {
    lines.push(`| # | Decision | Status | Task |`, `|---|---|---|---|`);
    for (const entry of entries) {
      lines.push(
        `| [${String(entry.number).padStart(4, '0')}](./${entry.file}) | ${entry.title} ` +
          `| ${entry.status} | ${entry.task ?? '—'} |`,
      );
    }
    lines.push(``);
  }

  lines.push(
    `## Superseding a decision`,
    ``,
    `Do not edit an accepted record to change its decision — the history is the`,
    `point. Write a new record, set the old one's Status to`,
    `\`superseded by NNNN\`, and say in the new one which it replaces.`,
    ``,
  );

  return lines.join('\n');
}

/** Rescan the directory and rewrite the index. Safe to call repeatedly. */
export function refreshAdrIndex(cwd: string): AdrEntry[] {
  ensureAdrDir(cwd);
  const entries = readAdrs(cwd);
  writeFileSync(join(cwd, ADR_DIR, 'README.md'), renderAdrIndex(entries), 'utf8');
  return entries;
}

/**
 * The instruction block handed to a worker. Carries the next free number so
 * the agent never has to list the directory to find it, and never collides —
 * tasks run one at a time, so the number is stable for the whole attempt.
 */
export function adrInstructions(nextNumber: number, taskId: string): string {
  const padded = String(nextNumber).padStart(4, '0');
  return `When you make a decision instead of asking, record it as an ADR:
create \`${ADR_DIR}/${padded}-<short-kebab-slug>.md\` with exactly this shape:

\`\`\`markdown
# ${padded}. <the decision, as a statement — "Use a token bucket for rate limiting">

- **Status:** accepted
- **Task:** ${taskId}
- **Reversal cost:** trivial | moderate | expensive

## Context
What forced a choice here. What in the repository or the task was ambiguous.

## Decision
What you did, specifically enough that someone could implement it the same way.

## Consequences
What this makes easy, what it makes hard, and what later work now has to
assume. Be honest about the downsides — a record listing only benefits is
not useful to the person who has to live with it.

## Alternatives considered
What else you weighed, and why you rejected it.
\`\`\`

If you make a second decision in this task, use \`${String(nextNumber + 1).padStart(4, '0')}\`, and so on.
Do not update the index — it is regenerated from the files.

Record a decision when the choice is architectural: a data model, a protocol,
a dependency, an interface, an error-handling strategy, a persistence choice.
Do NOT write a record for naming, formatting, or which of two equivalent
spellings to use. Those are just work.`;
}
